version: '3.1'

services:
  redis:
    image: 'redis:latest'
    container_name: 'redis-chat'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
